### ISSUE TITLE
The Collection Bundle Import should not require the spec_version property in the imported bundle

### ISSUE THREAD

**Issue by ElJocko** [center-for-threat-informed-defense/attack-workbench-rest-api#103]
~When exporting a collection bundle, the collection bundle service is not adding a `spec-version` property to the bundle. The `spec_version` is required and should be set to "2.1".~

**Comment by isaisabel** [comment]
The need for `spec_version` may not be correct. See this comment: https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/issues/247#issuecomment-925979804

**Comment by ElJocko** [comment]
When importing a collection bundle, the API should allow, but not require the `spec_version`.
